<?php

namespace Database\Seeders;

use App\Models\AdhocService;
use App\Models\Branch;
use App\Models\Scopes\BranchScope;
use Illuminate\Database\Seeder;

class AdhocServiceSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $services = [
            ['name' => 'Replaced Compressor for Chiller 1 Door Gas R134a', 'min_amount' => 520.00, 'max_amount' => 1050.00],
            ['name' => 'Replaced Compressor for Chiller 2 Door Gas R134a', 'min_amount' => 1050.00, 'max_amount' => 1250.00],
            ['name' => 'Replaced Compressor for Chiller 3 Door Gas R134a', 'min_amount' => 1150.00, 'max_amount' => 1250.00],
            ['name' => 'Replaced Compressor for Chiller 3 Door Gas R290', 'min_amount' => 1350.00, 'max_amount' => 1650.00],
            ['name' => 'Replaced Compressor for Chiller 1 Door Gas R290', 'min_amount' => 1050.00, 'max_amount' => 1150.00],
            ['name' => 'Replaced Compressor for Chest Freezer Gas R290', 'min_amount' => 1050.00, 'max_amount' => 1150.00],
            ['name' => 'Replaced Compressor for Chest Freezer Gas R134a', 'min_amount' => 1050.00, 'max_amount' => 1150.00],
            ['name' => 'Replaced Compressor for IVT Chiller 1 Door Gas R290', 'min_amount' => 0, 'max_amount' => null],
            ['name' => 'Replaced Compressor for IVT Chiller 2 Door Gas R290', 'min_amount' => 0, 'max_amount' => null],
            ['name' => 'Replaced Compressor for IVT Chiller 3 Door Gas R290', 'min_amount' => 0, 'max_amount' => null],
            ['name' => 'Replaced Compressor for IVT Freezer 2 Door Gas R290', 'min_amount' => 0, 'max_amount' => null],
            ['name' => 'Replaced Compressor for IVT Freezer 3 Door Gas R290', 'min_amount' => 0, 'max_amount' => null],
            ['name' => 'Replaced Compressor for Chiller/Freezer 2168', 'min_amount' => 1420.00, 'max_amount' => 1650.00],
            ['name' => 'Replaced Compressor for Freezer 3 Door 2180', 'min_amount' => 1750.00, 'max_amount' => 1950.00],
            ['name' => 'Replaced Compressor for Freezer 3 Door CAJ2464A', 'min_amount' => 1850.00, 'max_amount' => 2850.00],
            ['name' => 'Comp Motor+related works-1.2C/Chiller', 'min_amount' => 1050.00, 'max_amount' => 1450.00],
            ['name' => 'Comp Motor+related works-1.2C/Freezer', 'min_amount' => 1150.00, 'max_amount' => 1650.00],
            ['name' => 'Comp Motor+related works-1.5C/Chiller', 'min_amount' => 1050.00, 'max_amount' => 1450.00],
            ['name' => 'Comp Motor+related works-1.5C/Freezer', 'min_amount' => 1250.00, 'max_amount' => 1650.00],
            ['name' => 'Comp Motor+related works-B/room Freezer', 'min_amount' => 1450.00, 'max_amount' => 1850.00],
            ['name' => 'Replaced Compressor Accessories for Chiller - Overload', 'min_amount' => 40.00, 'max_amount' => 120.00],
            ['name' => 'Replaced Compressor Accessories for Chiller - Relay', 'min_amount' => 40.00, 'max_amount' => 120.00],
            ['name' => 'Replaced Compressor Accessories for Chiller - Capacitor', 'min_amount' => 40.00, 'max_amount' => 120.00],
            ['name' => 'Replaced Compressor Accessories for Chiller - Set', 'min_amount' => 120.00, 'max_amount' => 360.00],
            ['name' => 'Replaced Compressor Accessories for Freezer - Set', 'min_amount' => 180.00, 'max_amount' => 540.00],
            ['name' => 'Replaced Condensing Coil Heater for Freezer 3 Door', 'min_amount' => 128.00, 'max_amount' => 180.00],
            ['name' => 'Replaced Blower Coil Heater for Freezer 2 Door', 'min_amount' => 200.00, 'max_amount' => 250.00],
            ['name' => 'Replaced Blower Coil Heater for Freezer 3 Door', 'min_amount' => 219.00, 'max_amount' => 350.00],
            ['name' => 'Install Blower Water Plate Heater', 'min_amount' => 200.00, 'max_amount' => 250.00],
            ['name' => 'Install Blower Elbow Heater', 'min_amount' => 150.00, 'max_amount' => 180.00],
            ['name' => 'Replaced Solenoid Valve - Hot pipe', 'min_amount' => 90.00, 'max_amount' => 680.00],
            ['name' => 'Replaced Heater L', 'min_amount' => 60.00, 'max_amount' => 160.00],
            ['name' => 'Replaced Blower Cooling Coil for Chiller 1 Door', 'min_amount' => 270.00, 'max_amount' => 480.00],
            ['name' => 'Replaced Blower Cooling Coil for Chiller 2 Door', 'min_amount' => 420.00, 'max_amount' => 580.00],
            ['name' => 'Replaced Blower Cooling Coil for Chiller 3 Door', 'min_amount' => 600.00, 'max_amount' => 680.00],
            ['name' => 'Replaced Blower Cooling Coil for Freezer 1 Door', 'min_amount' => 0, 'max_amount' => null],
            ['name' => 'Replaced Blower Cooling Coil for Freezer 2 Door', 'min_amount' => 0, 'max_amount' => null],
            ['name' => 'Replaced Blower Cooling Coil for Freezer 3 Door', 'min_amount' => 680.00, 'max_amount' => 1150.00],
            ['name' => 'Replaced Cooling Coil Condensing type - Counter Chiller', 'min_amount' => 0, 'max_amount' => null],
            ['name' => 'Replaced Cooling Coil Condensing type - Counter Freezer', 'min_amount' => 0, 'max_amount' => null],
            ['name' => 'Replaced Cooling Coil Condensing type - Upright Freezer', 'min_amount' => 0, 'max_amount' => null],
            ['name' => 'Replaced Blower Condenser for Chiller 1 Door', 'min_amount' => 160.00, 'max_amount' => 260.00],
            ['name' => 'Replaced Blower Condenser for Chiller 2 Door', 'min_amount' => 180.00, 'max_amount' => 280.00],
            ['name' => 'Replaced Blower Condenser for Chiller 3 Door', 'min_amount' => 220.00, 'max_amount' => 320.00],
            ['name' => 'Replaced Blower Condenser for Freezer 1 Door', 'min_amount' => 360.00, 'max_amount' => 460.00],
            ['name' => 'Replaced Blower Condenser for Freezer 2 Door', 'min_amount' => 490.00, 'max_amount' => 590.00],
            ['name' => 'Replaced Blower Condenser for Freezer 3 Door (URF)', 'min_amount' => 680.00, 'max_amount' => 880.00],
            ['name' => 'Replaced 1/2hp Condenser Coil', 'min_amount' => 180.00, 'max_amount' => 480.00],
            ['name' => 'Replaced 3/4hp Condenser Coil', 'min_amount' => 200.00, 'max_amount' => 580.00],
            ['name' => 'Replaced 1hp Condenser Coil', 'min_amount' => 250.00, 'max_amount' => 550.00],
            ['name' => 'Replaced 1 1/2hp Condenser Coil', 'min_amount' => 360.00, 'max_amount' => 680.00],
            ['name' => 'Replaced 2hp Condenser Coil', 'min_amount' => 490.00, 'max_amount' => 980.00],
            ['name' => 'Replaced Polystrene box for Counter Chiller/Freezer', 'min_amount' => 0, 'max_amount' => null],
            ['name' => 'Replaced Polystrene box for Upright Freezer', 'min_amount' => 0, 'max_amount' => null],
            ['name' => 'Replaced C/bond Blower Water Plate for 1 Door', 'min_amount' => 80.00, 'max_amount' => 280.00],
            ['name' => 'Replaced C/bond Blower Water Plate for 2 Door', 'min_amount' => 120.00, 'max_amount' => 380.00],
            ['name' => 'Replaced C/bond Blower Water Plate for 3 Door', 'min_amount' => 160.00, 'max_amount' => 480.00],
            ['name' => 'Replaced S/Steel Blower Water Plate for 1 Door', 'min_amount' => 380.00, 'max_amount' => 480.00],
            ['name' => 'Replaced S/Steel Blower Water Plate for 2 Door', 'min_amount' => 480.00, 'max_amount' => 580.00],
            ['name' => 'Replaced S/Steel Blower Water Plate for 3 Door (diff. coil size)', 'min_amount' => 600.00, 'max_amount' => 880.00],
            ['name' => 'Replaced Filter Drier 032s (2/8)', 'min_amount' => 35.00, 'max_amount' => null],
            ['name' => 'Replaced Filter Drier 052s (2/8)', 'min_amount' => 38.00, 'max_amount' => null],
            ['name' => 'Replaced Filter Drier 083s (3/8)', 'min_amount' => 45.00, 'max_amount' => null],
            ['name' => 'Replaced Copper Filter', 'min_amount' => 30.00, 'max_amount' => null],
            ['name' => 'Replaced Capillary', 'min_amount' => 26.00, 'max_amount' => null],
            ['name' => 'Install Expansion Valve', 'min_amount' => 680.00, 'max_amount' => 980.00],
            ['name' => 'Install Access Valve', 'min_amount' => 280.00, 'max_amount' => 320.00],
            ['name' => 'Replaced Digital Sensor wire', 'min_amount' => 40.00, 'max_amount' => null],
            ['name' => 'Replaced Digital Controller for Chiller-Imax DS248', 'min_amount' => 160.00, 'max_amount' => null],
            ['name' => 'Replaced Digital Controller for Chiller-Imax HK70', 'min_amount' => 220.00, 'max_amount' => null],
            ['name' => 'Replaced Digital Controller for Chiller-Imax DS448', 'min_amount' => 40.00, 'max_amount' => null],
            ['name' => 'Replaced Digital Controller for Chiller-Imax SF-285V2', 'min_amount' => 220.00, 'max_amount' => null],
            ['name' => 'Replaced Digital Box SF-285V', 'min_amount' => 80.00, 'max_amount' => null],
            ['name' => 'Digital Controller Chiller-Imax SF121L', 'min_amount' => 300.00, 'max_amount' => 350.00],
            ['name' => 'Digital Controller Chiller-Imax SF820B', 'min_amount' => 420.00, 'max_amount' => null],
            ['name' => 'Digital Controller Chiller-Imax EZ12', 'min_amount' => 300.00, 'max_amount' => null],
            ['name' => 'For Chiller & Freezer IVT series HK-90', 'min_amount' => 500.00, 'max_amount' => 600.00],
            ['name' => 'THERMOSTAT AWTB-111F-C [CHILLER]', 'min_amount' => 120.00, 'max_amount' => null],
            ['name' => 'THERMOSTAT AWTB-111A-R [CHILLER & FREEZER]', 'min_amount' => 120.00, 'max_amount' => null],
            ['name' => 'Replaced Contactor MC-9B 240V', 'min_amount' => 250.00, 'max_amount' => null],
            ['name' => 'Replaced Relay 8 pin', 'min_amount' => 160.00, 'max_amount' => null],
            ['name' => 'Replace Blower Fan for Counter Chiller/Freezer', 'min_amount' => 280.00, 'max_amount' => 350.00],
            ['name' => 'Replace Video Fan 4"', 'min_amount' => 80.00, 'max_amount' => 180.00],
            ['name' => 'Replace Video Fan 6"', 'min_amount' => 100.00, 'max_amount' => 230.00],
            ['name' => 'Replaced Fan Motor YZF-8219', 'min_amount' => 35.00, 'max_amount' => null],
            ['name' => 'Replaced Fan Motor YZF-8225', 'min_amount' => 45.00, 'max_amount' => null],
            ['name' => 'Replaced Fan Motor YZF-8245', 'min_amount' => 85.00, 'max_amount' => null],
            ['name' => 'Replaced Fan Motor EC052', 'min_amount' => 75.00, 'max_amount' => 320.00],
            ['name' => 'Replaced Fan Motor EC072', 'min_amount' => 95.00, 'max_amount' => 380.00],
            ['name' => 'Replaced Fan Motor 5120', 'min_amount' => 0, 'max_amount' => null],
            ['name' => 'Replaced Fan Blade', 'min_amount' => 9.00, 'max_amount' => 50.00],
            ['name' => 'Replaced Fan Net', 'min_amount' => 12.50, 'max_amount' => 50.00],
            ['name' => 'Replaced Fan Stand', 'min_amount' => 9.60, 'max_amount' => 50.00],
            ['name' => 'Replaced Door Spring', 'min_amount' => 4.00, 'max_amount' => 50.00],
            ['name' => 'Replaced Door Hinges', 'min_amount' => 28.00, 'max_amount' => 80.00],
            ['name' => 'Replaced Door Gasket', 'min_amount' => 74.00, 'max_amount' => 200.00],
            ['name' => 'Replaced Dimmer', 'min_amount' => 30.00, 'max_amount' => 80.00],
            ['name' => 'Replaced S/Steel Solid Door for Counter series', 'min_amount' => 400.00, 'max_amount' => 550.00],
            ['name' => 'Replaced S/Steel Solid Door for Upright series', 'min_amount' => 500.00, 'max_amount' => 650.00],
            ['name' => 'Replaced Glass Door Chiller - Non Heater', 'min_amount' => 480.00, 'max_amount' => 580.00],
            ['name' => 'Replaced Glass Door Chiller - Heater Line', 'min_amount' => 580.00, 'max_amount' => 680.00],
            ['name' => 'Replaced Tempered Glass Door Chiller', 'min_amount' => 580.00, 'max_amount' => 880.00],
            ['name' => 'Replaced Tempered Glass Door Freezer', 'min_amount' => 680.00, 'max_amount' => 1080.00],
            ['name' => 'Replaced Tempered Glass Door Big Body', 'min_amount' => 2000.00, 'max_amount' => 2300.00],
            ['name' => 'Refill Gas for Chiller', 'min_amount' => 120.00, 'max_amount' => 160.00],
            ['name' => 'Refill Gas for Freezer', 'min_amount' => 120.00, 'max_amount' => 200.00],
            ['name' => 'Replaced Back Water Tray', 'min_amount' => 60.00, 'max_amount' => 80.00],
            ['name' => 'Replaced S/Steel Water Tray', 'min_amount' => 44.00, 'max_amount' => 80.00],
            ['name' => 'Replaced Copper Heater for Drain Pan', 'min_amount' => 55.00, 'max_amount' => 80.00],
            ['name' => 'Replaced Led Lamp 900mm', 'min_amount' => 60.00, 'max_amount' => 80.00],
            ['name' => 'Replaced Led Lamp 1200mm', 'min_amount' => 23.50, 'max_amount' => 80.00],
            ['name' => 'Replaced Led Lamp T5 1400mm', 'min_amount' => 26.00, 'max_amount' => 80.00],
            ['name' => 'Replaced Led Lamp 1400mm', 'min_amount' => 36.00, 'max_amount' => 100.00],
            ['name' => 'Replaced On Off Switch Small', 'min_amount' => 5.00, 'max_amount' => 30.00],
            ['name' => 'Replaced On Off Switch Big', 'min_amount' => 15.00, 'max_amount' => 50.00],
            ['name' => 'Replaced Center Pole Non Heater 1725*100*50mm Black & White', 'min_amount' => 750.00, 'max_amount' => 850.00],
            ['name' => 'Replaced Center Pole Non Heater 1705*95*47mm Black & White', 'min_amount' => 750.00, 'max_amount' => 850.00],
            ['name' => 'Jhr Zone 1 - Gen. Main. Transport Charge', 'min_amount' => 80.00, 'max_amount' => 100.00],
            ['name' => 'Jhr Zone 2 - Gen. Main. Transport Charge', 'min_amount' => 80.00, 'max_amount' => 100.00],
            ['name' => 'Jhr Zone 3 - Gen. Main. Transport Charge', 'min_amount' => 80.00, 'max_amount' => 100.00],
            ['name' => 'Jhr Zone 4 - Gen. Main. Transport Charge', 'min_amount' => 120.00, 'max_amount' => 250.00],
            ['name' => 'Ked Zone 1 - Gen. Main. Transport Charge', 'min_amount' => 80.00, 'max_amount' => 100.00],
            ['name' => 'Ked Zone 2 - Gen. Main. Transport Charge', 'min_amount' => 80.00, 'max_amount' => 120.00],
            ['name' => 'Ked Zone 3 - Gen. Main. Transport Charge', 'min_amount' => 80.00, 'max_amount' => 180.00],
            ['name' => 'Ked Zone 4 - Gen. Main. Transport Charge', 'min_amount' => 100.00, 'max_amount' => 250.00],
            ['name' => 'Klt Zone 1 - Gen. Main. Transport Charge', 'min_amount' => 80.00, 'max_amount' => 100.00],
            ['name' => 'Klt Zone 2 - Gen. Main. Transport Charge', 'min_amount' => 80.00, 'max_amount' => 120.00],
            ['name' => 'Klt Zone 3 - Gen. Main. Transport Charge', 'min_amount' => 80.00, 'max_amount' => 180.00],
            ['name' => 'Klt Zone 4 - Gen. Main. Transport Charge', 'min_amount' => 100.00, 'max_amount' => 250.00],
            ['name' => 'Kv Zone 1 - Gen. Main. Transport Charge', 'min_amount' => 50.00, 'max_amount' => 100.00],
            ['name' => 'Kv Zone 3 - Gen. Main. Transport Charge', 'min_amount' => 100.00, 'max_amount' => 180.00],
            ['name' => 'Mk Zone 1 - Gen. Main. Transport Charge', 'min_amount' => 80.00, 'max_amount' => 150.00],
            ['name' => 'Ns Zone 1 - Gen. Main. Transport Charge', 'min_amount' => 80.00, 'max_amount' => 150.00],
            ['name' => 'Ns Zone 3 - Gen. Main. Transport Charge', 'min_amount' => 100.00, 'max_amount' => 180.00],
            ['name' => 'Phg Zone 1 - Gen. Main. Transport Charge', 'min_amount' => 80.00, 'max_amount' => 100.00],
            ['name' => 'Phg Zone 2 - Gen. Main. Transport Charge', 'min_amount' => 100.00, 'max_amount' => 120.00],
            ['name' => 'Phg Zone 3 - Gen. Main. Transport Charge', 'min_amount' => 120.00, 'max_amount' => 180.00],
            ['name' => 'Phg Zone 4 - Gen. Main. Transport Charge', 'min_amount' => 150.00, 'max_amount' => 250.00],
            ['name' => 'Trg Zone 1 - Gen. Main. Transport Charge', 'min_amount' => 80.00, 'max_amount' => 100.00],
            ['name' => 'Trg Zone 3 - Gen. Main. Transport Charge', 'min_amount' => 80.00, 'max_amount' => 180.00],
            ['name' => 'Per Zone 2 - Gen. Main. Transport Charge', 'min_amount' => 100.00, 'max_amount' => 250.00],
            ['name' => 'Pg Zone 1 - Gen. Main. Transport Charge', 'min_amount' => 50.00, 'max_amount' => 100.00],
            ['name' => 'Prk Zone 1 - Gen. Main. Transport Charge', 'min_amount' => 80.00, 'max_amount' => 100.00],
            ['name' => 'Prk Zone 2 - Gen. Main. Transport Charge', 'min_amount' => 80.00, 'max_amount' => 100.00],
            ['name' => 'Prk Zone 3 - Gen. Main. Transport Charge', 'min_amount' => 80.00, 'max_amount' => 100.00],
            ['name' => 'Prk Zone 4 - Gen. Main. Transport Charge', 'min_amount' => 100.00, 'max_amount' => 250.00],
            ['name' => 'Sbh Zone 1 - Gen. Main. Transport Charge (KK)', 'min_amount' => 0, 'max_amount' => null],
            ['name' => 'Sbh Zone 2 - Gen. Main. Transport Charge (Outside KK)', 'min_amount' => 0, 'max_amount' => null],
            ['name' => 'Srk Zone 1 - Gen. Main. Transport Charge (Kuching)', 'min_amount' => 0, 'max_amount' => null],
            ['name' => 'Srk Zone 2 - Gen. Main. Transport Charge (Outside Kuching)', 'min_amount' => 0, 'max_amount' => null],
            ['name' => 'Repairing Workmanship - Checking & Troubleshoot', 'min_amount' => 50.00, 'max_amount' => 180.00],
            ['name' => 'Service Workmanship - Cleaning Condenser', 'min_amount' => 30.00, 'max_amount' => 100.00],
        ];

        $adhocService = new AdhocService;

        foreach ($services as $serviceData) {
            $exists = AdhocService::withoutGlobalScope(BranchScope::class)
                ->where('name', $serviceData['name'])
                ->exists();

            if ($exists) {
                continue;
            }

            $service = AdhocService::create([
                'sku' => $adhocService->generateSku(),
                'name' => $serviceData['name'],
                'min_amount' => $serviceData['min_amount'],
                'max_amount' => $serviceData['max_amount'],
                'is_active' => true,
            ]);

            (new Branch)->assign(AdhocService::class, $service->id, Branch::LOCATION_KL);
        }
    }
}
